---
- name: Prometheus Configuration play
  hosts: web
  gather_facts: no
  pre_tasks:
    - name: Ensure python 3 available
      become: yes
      apt:
        name: python3
        state: present
    - name: Wait for port 22
      wait_for:
        port: 22
        delay: 10
  tasks:
    - name: Ensure prometheus group exists
      become: yes
      group:
        name: prometheus
        state: present

    - name: Ensure prometheus user exists
      become: yes
      user:
        name: prometheus
        create_home: no
        group: prometheus

    - name: Check prometheus folder existing
      stat:
        path: ~/prometheus
      register: folder_state

    - name: Extract prometheus binary
      unarchive:
        src: https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
        dest: ~/
        remote_src: yes
      when: not folder_state.stat.exists

    - name: Rename prometheus folder
      shell: sudo mv ~/prometheus-2.19.0.linux-amd64 ~/prometheus
      when: not folder_state.stat.exists

    - name: Copy prometheus config
      copy:
        src: ./files/prometheus.yml
        dest: ~/prometheus

    - name: Copy prometheus service
      become: yes
      copy:
        src: ./files/prometheus.service
        dest: /etc/systemd/system

    # - name: Ensure prometheus permissions applied
    #   become: yes
    #   shell: sudo chown -R prometheus:prometheus ~/prometheus

    # - name: Ensure prometheus runs as a service
    #   become: yes
    #   systemd:
    # name: node_exporter
    # state: restarted
    # daemon_reload: yes
    # enabled: yes

    - name: Run prometheus
      become: yes
      shell: |
        cd ~/prometheus
        ./prometheus &

    - name: Ensure prometheus is running
      shell: ps aux | grep prometheus
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
