Description: >
  Prometheus server stack.

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Prometheus-SG
      GroupDescription: Allow inbound access to prometheus ports
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9093
          ToPort: 9093
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0

  EC2AccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PrometheusEC2AccessRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
      Tags:
        - Key: Name
          Value: PrometheusEC2AccessRole

  InstanceProfileRoles:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: PrometheusEC2Profile
      Roles:
        - Ref: EC2AccessRole

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udapeople
      ImageId: ami-0d527b8c289b4af7f
      IamInstanceProfile: !Ref InstanceProfileRoles
      Tags:
        - Key: Name
          Value: prometheus-server

Outputs:
  InstanceIP:
    Description: EC2 instance public IP
    Value: !GetAtt EC2Instance.PublicIp
